<a href="https://colab.research.google.com/github/Arpit1118/Pytorch/blob/main/Common_Torch_Dump.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Autograd
import torch
x= torch.rand(3,requires_grad=True)
print(x)
y = x+2
print(y)
z=y*y*2
z = z.mean() #Has to be a scaler value
print(z)

z.backward()  #dz/dx
print(x.grad)
#Chain rule example


#detach(), with torch.no_grad() functions remove the requires_grad, basically make it false.

tensor([0.7579, 0.3502, 0.2197], requires_grad=True)
tensor([2.7579, 2.3502, 2.2197], grad_fn=<AddBackward0>)
tensor(12.0379, grad_fn=<MeanBackward0>)
tensor([3.6773, 3.1336, 2.9596])


In [2]:
# Forward and Backward Pass
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad = True)

#Forward pass
y_cap = w*x
loss = (y_cap-y)**2
print(loss)

#Backward pass
loss.backward()
print(w.grad)

#update weights
#next forward and backward pass

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [3]:
#Autograd
import numpy as np
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)

w = 0.0
#model prediction
def forward(x):
  return w*X
#loss = MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()

#gradient
#MSE = 1/N * (w*x - y)**2
#dJ/dw = 1/N * 2x(w*x - y)
def gradient(x,y,y_predicted):
  return np.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5)[0]:.3f}')
#Training
learning_rate = 0.01
n_iters = 20
for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)
  #loss
  l = loss(Y,y_pred)
  #gradients
  dw = gradient(X,Y,y_pred)
  #update weights
  w -= learning_rate*dw
  if epoch % 1 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5)[0]:.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 2: w = 1.680, loss = 4.80000067
epoch 3: w = 1.872, loss = 0.76800019
epoch 4: w = 1.949, loss = 0.12288000
epoch 5: w = 1.980, loss = 0.01966083
epoch 6: w = 1.992, loss = 0.00314574
epoch 7: w = 1.997, loss = 0.00050332
epoch 8: w = 1.999, loss = 0.00008053
epoch 9: w = 1.999, loss = 0.00001288
epoch 10: w = 2.000, loss = 0.00000206
epoch 11: w = 2.000, loss = 0.00000033
epoch 12: w = 2.000, loss = 0.00000005
epoch 13: w = 2.000, loss = 0.00000001
epoch 14: w = 2.000, loss = 0.00000000
epoch 15: w = 2.000, loss = 0.00000000
epoch 16: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 18: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
epoch 20: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 2.000


In [4]:
#Autograd
import torch
X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32)

w = torch.tensor(0.0, dtype = torch.float32, requires_grad=True)
#model prediction
def forward(x):
  return w*X
#loss = MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()

print(f'Prediction before training: f(5) = {forward(5)[0]:.3f}')
#Training
learning_rate = 0.01
n_iters = 20
for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)
  #loss
  l = loss(Y,y_pred)
  #gradients=backward pass
  l.backward() #dl/dw
  #update weights
  with torch.no_grad():
    w -= learning_rate*w.grad
  #zero gradients
  w.grad.zero_()
  if epoch % 1 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5)[0]:.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 2: w = 0.555, loss = 21.67499924
epoch 3: w = 0.772, loss = 15.66018772
epoch 4: w = 0.956, loss = 11.31448650
epoch 5: w = 1.113, loss = 8.17471695
epoch 6: w = 1.246, loss = 5.90623236
epoch 7: w = 1.359, loss = 4.26725292
epoch 8: w = 1.455, loss = 3.08308983
epoch 9: w = 1.537, loss = 2.22753215
epoch 10: w = 1.606, loss = 1.60939169
epoch 11: w = 1.665, loss = 1.16278565
epoch 12: w = 1.716, loss = 0.84011245
epoch 13: w = 1.758, loss = 0.60698116
epoch 14: w = 1.794, loss = 0.43854395
epoch 15: w = 1.825, loss = 0.31684780
epoch 16: w = 1.851, loss = 0.22892261
epoch 17: w = 1.874, loss = 0.16539653
epoch 18: w = 1.893, loss = 0.11949898
epoch 19: w = 1.909, loss = 0.08633806
epoch 20: w = 1.922, loss = 0.06237914
Prediction after training: f(5) = 1.922


In [5]:
#1)Design model (inputs, outputs, forward pass)
#2)Construct loss and optimizer
#3)Training loop
# -Forward pass: compute prediction
# -backward pass: gradients
# -update weights
#Check other notebooks for automatic gradients and loss calculations. The above ones are for manual calculation.

In [6]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
%matplotlib inline

#0) Data Preparation
X_numpy, y_numpy = datasets.make_regression(n_samples = 100, n_features = 1, noise = 20, random_state=1)
X = torch.from_numpy(X_numpy.astype(np.float32))
y = torch.from_numpy(y_numpy.astype(np.float32))
y = y.view(y.shape[0],1)

n_samples, n_features = X.shape

#1)model
input_size = n_features
output_size = 1
model = nn.Linear(input_size, output_size)

#2)loss and optimizer

criterion = nn.MSELoss()
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#3)Training loop
num_epochs = 100
for epoch in range(num_epochs):
  #forward pass and loss
  y_predicted = model(X)
  loss = criterion(y_predicted, y)

  #backward pass
  loss.backward()

  #update
  optimizer.step()
  optimizer.zero_grad()

  if (epoch+1) % 10 == 0:
    print(f'epoch: {epoch+1}, loss = {loss.item(): .4f}')

epoch: 10, loss =  4475.7095
epoch: 20, loss =  3335.3137
epoch: 30, loss =  2510.8665
epoch: 40, loss =  1914.1617
epoch: 50, loss =  1481.8370
epoch: 60, loss =  1168.3049
epoch: 70, loss =  940.7214
epoch: 80, loss =  775.3884
epoch: 90, loss =  655.1877
epoch: 100, loss =  567.7380


In [7]:
# epoch = one forward and backward pass of ALL training samples
# batch_size = number of training samples used in one forward/backward pass
# number of iterations = number of passes, each pass (forward+backward) using [batch_size] number of sampes
# e.g : 100 samples, batch_size=20 -> 100/20=5 iterations for 1 epoch

In [8]:
#Batch Training using DataLoader
#dataloader = DataLoader(dataset = my_dataset, batchsize = 5, shuffle = True, num_workers = 2)
#dataiter = iter(dataloader)
#data = dataiter.next()
#features, labels = data
#print(features, labels)

In [9]:
#Softmax example
import torch
import torch.nn as nn
import numpy as np

def softmax(x):
  return np.exp(x)/np.sum(np.exp(x), axis = 0)
x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print('softmax numpy:', outputs)

x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0) # along values along first axis
print('softmax torch:', outputs)


softmax numpy: [0.65900114 0.24243297 0.09856589]
softmax torch: tensor([0.6590, 0.2424, 0.0986])


In [10]:
#Cross-Entropy Example
loss = nn.CrossEntropyLoss()
Y = torch.tensor([2, 0, 1])

# input is of size nBatch x nClasses = 3 x 3
# Y_pred are logits (not softmax)
Y_pred_good = torch.tensor(
    [[0.1, 0.2, 3.9], # predict class 2
    [1.2, 0.1, 0.3], # predict class 0
    [0.3, 2.2, 0.2]]) # predict class 1

Y_pred_bad = torch.tensor(
    [[0.9, 0.2, 0.1],
    [0.1, 0.3, 1.5],
    [1.2, 0.2, 0.5]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)
print(f'Batch Loss1:  {l1.item():.4f}')
print(f'Batch Loss2: {l2.item():.4f}')

# get predictions
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(f'Actual class: {Y}, Y_pred1: {predictions1}, Y_pred2: {predictions2}')


Batch Loss1:  0.2834
Batch Loss2: 1.6418
Actual class: tensor([2, 0, 1]), Y_pred1: tensor([2, 0, 1]), Y_pred2: tensor([0, 2, 0])


In [11]:
#Most Common activation functions
#1) Step function - 1/1+exp(-x), used for Binary classification problem  [0,1]
#2) Sigmoid - 1/1+exp(-x), used for Binary classification problem  [0,1]
#3) TanH - (2/1+exp(2x)) -1 Used in hidden layers. [-1,1]
#4) ReLU- max(0,x) mostly use [0,infinite] non linear
#5) Leaky ReLU - extension of ReLU solve vanishing gradient problem.
#6) softmax- Used in multi-class classification, converts logits to probabilities.