<a href="https://colab.research.google.com/github/Arpit1118/Pytorch/blob/main/Common_Torch_Dump.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Autograd
import torch
x= torch.rand(3,requires_grad=True)
print(x)
y = x+2
print(y)
z=y*y*2
z = z.mean() #Has to be a scaler value
print(z)

z.backward()  #dz/dx
print(x.grad)
#Chain rule example


#detach(), with torch.no_grad() functions remove the requires_grad, basically make it false.

tensor([0.2022, 0.3378, 0.9203], requires_grad=True)
tensor([2.2022, 2.3378, 2.9203], grad_fn=<AddBackward0>)
tensor(12.5622, grad_fn=<MeanBackward0>)
tensor([2.9363, 3.1171, 3.8938])


In [2]:
# Forward and Backward Pass
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad = True)

#Forward pass
y_cap = w*x
loss = (y_cap-y)**2
print(loss)

#Backward pass
loss.backward()
print(w.grad)

#update weights
#next forward and backward pass

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [3]:
#Autograd
import numpy as np
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)

w = 0.0
#model prediction
def forward(x):
  return w*X
#loss = MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()

#gradient
#MSE = 1/N * (w*x - y)**2
#dJ/dw = 1/N * 2x(w*x - y)
def gradient(x,y,y_predicted):
  return np.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5)[0]:.3f}')
#Training
learning_rate = 0.01
n_iters = 10
for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)
  #loss
  l = loss(Y,y_pred)
  #gradients
  dw = gradient(X,Y,y_pred)
  #update weights
  w -= learning_rate*dw
  if epoch % 1 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5)[0]:.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 2: w = 1.680, loss = 4.80000067
epoch 3: w = 1.872, loss = 0.76800019
epoch 4: w = 1.949, loss = 0.12288000
epoch 5: w = 1.980, loss = 0.01966083
epoch 6: w = 1.992, loss = 0.00314574
epoch 7: w = 1.997, loss = 0.00050332
epoch 8: w = 1.999, loss = 0.00008053
epoch 9: w = 1.999, loss = 0.00001288
epoch 10: w = 2.000, loss = 0.00000206
Prediction after training: f(5) = 2.000
