<a href="https://colab.research.google.com/github/Arpit1118/Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.05582985, 0.99106763, 0.70317376, 0.81458376],
       [0.09357568, 0.8269244 , 0.52652851, 0.51563771],
       [0.09089621, 0.86828803, 0.73445757, 0.92914085]])

In [4]:
np1.dtype

dtype('float64')

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.5249,  0.1446,  0.6334,  0.8238],
        [ 0.2125,  0.8265, -0.4010, -0.3856],
        [-0.7768,  0.5225,  2.2600,  2.0408]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
#Numpy array into Torch array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0558, 0.9911, 0.7032, 0.8146],
        [0.0936, 0.8269, 0.5265, 0.5156],
        [0.0909, 0.8683, 0.7345, 0.9291]], dtype=torch.float64)